travis:
  secure:
    BINSTAR_TOKEN: vLOJS9wEqjZW2C4SfKE24YkxAjNQlw0xoqYoNaFRkXr0/zsEZWzf23URlTmWl376spt7Vt7HRS76tQAYh+8Ead0YIrqRMJqxa3WdfD558/mKgRs/KRjuDCr1G6qfDi2ucK5t+xgiVTE6E0Rq9zxOmP3FJx7U2tyNe72LPOLN9LCazloYdn513lkBKOV38IprRJkYnsQ+JTYqxAF01HuL6MHj+WfEywl6prKmyP0g2wqQxKNoCiEiS8EMZAmVb8Fd+0loMyU/64eSFNGZgaaAfh0NpI4ht0ny35xBkRczODuw7tGnZQyWLPsSMwhqNI2y2xNbFQYh5aR8AeL+tbALG5r4+I72WUk0Vi9Aqaj7Cz9l8REdbYVOnl34FYUU+EtYOxIB9Tn5b/Nr40DaSXMifPpRfP2/hjXU7Z86dlDHuAthVRom73KVJdf5jiqtDeKqqSHYrLjVitRI9Rign4qrSmirQDGGuh+Uj5rorq8ZpCTK0LKVYmA7OhpiFjepefn/zee4Oi013xGoJWUGx3OvEA6ujFnBwfB18MYaeHjKlfxBMKtXtZNqaQFnDy4lY2YMHhKQcpBs1c2BmHizY0WJP7ZM6kLZNDV+mxo4O4pEXwd+3rqwradEmDqq7e+BIqWaRA/w/S4Rh4DOPjTy1pS7QTd0YjRaJzOv0wCPPU0cmh8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
